#!/usr/bin/perl
use strict; use warnings; use CGI; use JSON::PP; use LoxBerry::System; use LoxBerry::Web;
my $q=CGI->new; my $cfgfile="$lbpconfigdir/config.json"; my $json=JSON::PP->new->utf8->pretty;
sub readcfg{open my $f,'<',$cfgfile or die 'Config fehlt';local $/;my $c=decode_json(<$f>);close $f;return $c}
sub esc{my $s=shift//'';$s=~s/&/&amp;/g;$s=~s/</&lt;/g;$s=~s/>/&gt;/g;$s=~s/"/&quot;/g;return $s}
my $msg='';
if(($q->param('action')//'') eq 'save'){
 my $c=readcfg();
 for my $k(qw(controller username password site controller_type api_token cycle_seconds)){$c->{$k}=$q->param($k)//''}
 $c->{verify_ssl}=($q->param('verify_ssl')//'') eq '1'?JSON::PP::true:JSON::PP::false;
 $c->{mqtt}||={};
 delete @{$c->{mqtt}}{qw(host port username password)};
 $c->{mqtt}{base_topic}=$q->param('mqtt_base_topic')//'unifipoe';
 $c->{mqtt}{enabled}=($q->param('mqtt_enabled')//'') eq '1'?JSON::PP::true:JSON::PP::false;
 $c->{mqtt}{retain}=($q->param('mqtt_retain')//'') eq '1'?JSON::PP::true:JSON::PP::false;
 $c->{watchdog}||={};$c->{watchdog}{enabled}=($q->param('watchdog_enabled')//'') eq '1'?JSON::PP::true:JSON::PP::false;
 $c->{debug}||={};$c->{debug}{level}=$q->param('debug_level')//'debug';
 my $aliases=$q->param('aliases_json')//'{}';my $groups=$q->param('groups_json')//'[]';
 eval{$c->{aliases}=decode_json($aliases);$c->{groups}=decode_json($groups);1} or $msg='Alias/Gruppen JSON ist ungültig.';
 if(!$msg){open my $f,'>',$cfgfile or die $!;chmod 0600,$cfgfile;print $f $json->encode($c);close $f;$msg='Einstellungen gespeichert.'}
}
my $c=readcfg();$c->{mqtt}||={};$c->{watchdog}||={};$c->{debug}||={};$c->{aliases}||={};$c->{groups}||=[];
my $aliases=esc(JSON::PP->new->canonical->pretty->encode($c->{aliases}));my $groups=esc(JSON::PP->new->canonical->pretty->encode($c->{groups}));
LoxBerry::Web::lbheader('UniFi PoE Control','https://www.loxberry.de','','nojqm');
print <<'CSS';
<style>
:root{--g:#72b62b;--line:#dde3e7;--text:#26313a;--muted:#6c7780;--red:#d63b37;--blue:#287fd3}*{box-sizing:border-box}.u{max-width:1450px;margin:auto;padding:12px;font-family:Arial,sans-serif;color:var(--text)}.head{display:flex;gap:14px;align-items:center;border-bottom:1px solid var(--line);padding:8px 0 14px;margin-bottom:14px}.logo{width:56px;height:56px;border-radius:10px;background:var(--g);display:grid;place-items:center;color:white;font-size:30px}.title{flex:1}.title h1{margin:0;color:#248737;font-size:24px}.title p{margin:4px 0 0;color:var(--muted)}.btn{border:1px solid #ccd4da;background:white;border-radius:6px;padding:8px 11px;cursor:pointer}.green{background:var(--g);border-color:var(--g);color:white}.red{color:var(--red)}.cards{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin-bottom:14px}.metric,.card{background:white;border:1px solid var(--line);border-radius:7px}.metric{padding:13px}.metric b{font-size:22px;display:block}.metric small{color:var(--muted)}.layout{display:grid;grid-template-columns:minmax(0,2fr) minmax(310px,.8fr);gap:14px}.card{margin-bottom:14px}.card h2{font-size:17px;margin:0;padding:12px 14px;border-bottom:1px solid #edf0f2}.body{padding:14px}.toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-bottom:10px}.toolbar input,.toolbar select,.field input,.field select,.field textarea{border:1px solid #cbd3d9;border-radius:5px;padding:8px;background:white}.toolbar input{flex:1}.field label{display:block;font-weight:bold;font-size:12px;margin:8px 0 4px}.field input,.field select,.field textarea{width:100%}.field textarea{height:120px;font-family:monospace}.grid{display:grid;grid-template-columns:repeat(2,minmax(250px,1fr));gap:12px}.checks{display:flex;gap:16px;flex-wrap:wrap;margin:12px 0}table{width:100%;border-collapse:collapse;font-size:13px}th,td{padding:8px;border-bottom:1px solid #e7eaed;text-align:left}th{background:#fafbfb}.pill{padding:3px 7px;border-radius:4px;background:#edf8e9;color:#287f2d}.pill.off{background:#f1f2f3;color:#666}.ok{color:#27892e}.bad{color:var(--red)}.notice{background:#eff9e9;border:1px solid #cae6ba;padding:9px 12px;margin-bottom:12px;border-radius:5px}.hide{display:none}.log{height:230px;overflow:auto;background:#fafafa;border:1px solid #e3e6e8;font:12px monospace;padding:8px;white-space:pre-wrap}.footer{text-align:center;padding:18px;color:#555}.mqttnote{background:#f4f8fb;border:1px solid #d7e4ed;border-radius:5px;padding:10px;margin-top:8px;color:#4d5962}@media(max-width:1000px){.cards{grid-template-columns:repeat(2,1fr)}.layout{grid-template-columns:1fr}}@media(max-width:650px){.cards,.grid{grid-template-columns:1fr}.head{flex-wrap:wrap}}
</style>
CSS
print '<div class="u"><div class="head"><div class="logo">⚡</div><div class="title"><h1>UniFi PoE Control</h1><p>PoE schalten &amp; überwachen für UniFi Switches · Version 0.5.0</p></div><button class="btn" onclick="selftest()">Selbsttest</button><button class="btn" onclick="toggleCfg()">Konfiguration</button></div>';
print '<div class="notice">'.esc($msg).'</div>' if $msg;
print <<'HTML';
<div class="cards"><div class="metric"><b id="msw">–</b>Switches<small id="msws">Noch nicht geladen</small></div><div class="metric"><b id="mport">–</b>PoE Ports<small id="mports">Noch nicht geladen</small></div><div class="metric"><b id="mpwr">–</b>Gesamt PoE<small>Verbrauch</small></div><div class="metric"><b id="mstat">…</b>System<small id="mstats">Prüfung ausstehend</small></div><div class="metric"><b id="mwd">…</b>Watchdog<small id="mwds">Status wird geladen</small></div></div>
<div class="layout"><main><section class="card"><h2>PoE Ports</h2><div class="body"><div class="toolbar"><select id="sw" onchange="render()"><option>Switches laden…</option></select><input id="filter" placeholder="Port suchen…" oninput="render()"><button class="btn" onclick="loadDevices()">Aktualisieren</button></div><div style="overflow:auto"><table><thead><tr><th>Port</th><th>Name</th><th>Status</th><th>Leistung</th><th>Link</th><th>Aktion</th></tr></thead><tbody id="ports"><tr><td colspan="6">Lade Daten…</td></tr></tbody></table></div></div></section><section class="card"><h2>Selbsttest</h2><div class="body" id="test">Noch kein Test ausgeführt.</div></section></main><aside><section class="card"><h2>Gruppen</h2><div class="body" id="groups"></div></section><section class="card"><h2>Watchdog</h2><div class="body" id="wd">Noch kein Status.</div></section></aside></div>
HTML
print '<section id="cfg" class="card hide"><h2>Konfiguration</h2><div class="body"><form method="post"><input type="hidden" name="action" value="save"><div class="grid">';
for my $f(['controller','Controller URL'],['username','UniFi Benutzer'],['password','UniFi Passwort'],['site','Site'],['api_token','HTTP API Token'],['cycle_seconds','Power-Cycle Sekunden']){print '<div class="field"><label>'.$f->[1].'</label><input name="'.$f->[0].'" value="'.esc($c->{$f->[0]}//'').'"></div>'}
print '<div class="field"><label>Controller-Typ</label><select name="controller_type"><option value="unifios"'.(($c->{controller_type}//'') eq 'unifios'?' selected':'').'>UniFi OS / UDM / CloudKey</option><option value="classic"'.(($c->{controller_type}//'') eq 'classic'?' selected':'').'>Classic Network Controller</option></select></div>';
print '<div class="field"><label>MQTT Basistopic</label><input name="mqtt_base_topic" value="'.esc($c->{mqtt}{base_topic}//'unifipoe').'"><div class="mqttnote"><b>LoxBerry MQTT</b><br>Broker, Port, Benutzer und Passwort werden automatisch aus der zentralen LoxBerry-MQTT-Konfiguration gelesen.</div></div>';
print '<div class="field"><label>Debug-Level</label><select name="debug_level">';for my $v(qw(debug info warning error)){print '<option value="'.$v.'"'.(($c->{debug}{level}//'debug') eq $v?' selected':'').'>'.$v.'</option>'}print '</select></div></div>';
print '<div class="checks"><label><input type="checkbox" name="verify_ssl" value="1"'.($c->{verify_ssl}?' checked':'').'> TLS prüfen</label><label><input type="checkbox" name="mqtt_enabled" value="1"'.($c->{mqtt}{enabled}?' checked':'').'> MQTT aktiv</label><label><input type="checkbox" name="mqtt_retain" value="1"'.($c->{mqtt}{retain}?' checked':'').'> Retain</label><label><input type="checkbox" name="watchdog_enabled" value="1"'.($c->{watchdog}{enabled}?' checked':'').'> Watchdog aktiv</label></div><div class="grid"><div class="field"><label>Port-Aliase (JSON)</label><textarea name="aliases_json">'.$aliases.'</textarea></div><div class="field"><label>Gruppen (JSON)</label><textarea name="groups_json">'.$groups.'</textarea></div></div><p><button class="btn green" type="submit">Speichern</button></p></form></div></section>';
print <<'HTML';
<section class="card"><h2>Debug Log</h2><div class="body"><div class="toolbar"><button class="btn" onclick="logLoad()">Aktualisieren</button><button class="btn red" onclick="logClear()">Log leeren</button></div><div id="log" class="log"></div></div></section><div class="footer">Marco Düthorn · 2026</div></div>
HTML
my $token=esc($c->{api_token});my $gj=encode_json($c->{groups});
print qq~<script>
const API='../html/poe.cgi',TOKEN='$token',GROUPS=$gj;let DEV=[];
const h=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(q){let r=await fetch(API+'?token='+encodeURIComponent(TOKEN)+'&'+q,{cache:'no-store'}),t=await r.text();let j;try{j=JSON.parse(t)}catch(e){throw Error(t.slice(0,200))}return j}
function toggleCfg(){document.getElementById('cfg').classList.toggle('hide');document.getElementById('cfg').scrollIntoView({behavior:'smooth'})}
async function loadDevices(){try{let j=await api('cmd=devices');if(!j.ok)throw Error(j.error||'API Fehler');DEV=j.devices||[];sw.innerHTML=DEV.map((d,i)=>'<option value="'+i+'">'+h(d.name||d.mac||d.id)+'</option>').join('');let n=DEV.reduce((a,d)=>a+(d.ports||[]).length,0),p=DEV.reduce((a,d)=>a+(d.ports||[]).reduce((b,x)=>b+(parseFloat(x.poe_power)||0),0),0);msw.textContent=DEV.length;msws.textContent='Online: '+DEV.length;mport.textContent=n;mports.textContent='Erkannt: '+n;mpwr.textContent=p.toFixed(1)+' W';render()}catch(e){ports.innerHTML='<tr><td colspan="6" class="bad">'+h(e.message)+'</td></tr>'}}
function render(){let d=DEV[parseInt(sw.value||0)];if(!d)return;let f=filter.value.toLowerCase();ports.innerHTML=(d.ports||[]).filter(p=>JSON.stringify(p).toLowerCase().includes(f)).map(p=>{let on=(p.poe_mode||'auto')!=='off',name=p.alias||p.name||('Port '+p.port_idx),wat=parseFloat(p.poe_power)||0;return '<tr><td>'+p.port_idx+'</td><td>'+h(name)+'</td><td><span class="pill '+(on?'':'off')+'">'+(on?'Ein':'Aus')+'</span></td><td>'+wat.toFixed(1)+' W</td><td>'+(p.link_up?'<span class="ok">Online</span>':'–')+'</td><td><button class="btn green" onclick="act(\''+h(d.id)+'\','+p.port_idx+',\'on\')">Ein</button> <button class="btn" onclick="act(\''+h(d.id)+'\','+p.port_idx+',\'cycle\')">Cycle</button> <button class="btn red" onclick="act(\''+h(d.id)+'\','+p.port_idx+',\'off\')">Aus</button></td></tr>'}).join('')||'<tr><td colspan="6">Keine Ports.</td></tr>'}
async function act(s,p,c){let j=await api('cmd='+c+'&switch='+encodeURIComponent(s)+'&port='+p);if(!j.ok)alert(j.error||'Fehler');setTimeout(loadDevices,c==='cycle'?1200:400)}
function renderGroups(){groups.innerHTML=GROUPS.length?GROUPS.map(g=>'<p><b>'+h(g.name)+'</b> ('+(g.ports||[]).length+') <button class="btn green" onclick="gact(\''+encodeURIComponent(g.name)+'\',\'group-on\')">Ein</button> <button class="btn red" onclick="gact(\''+encodeURIComponent(g.name)+'\',\'group-off\')">Aus</button></p>').join(''):'Noch keine Gruppen.'}
async function gact(g,c){let j=await api('cmd='+c+'&group='+g);if(!j.ok)alert(j.error||'Fehler');loadDevices()}
async function selftest(){test.textContent='Prüfung läuft…';try{let j=await api('cmd=selftest');test.innerHTML=(j.tests||[]).map(t=>'<div class="'+(t.ok?'ok':'bad')+'">'+(t.ok?'✓':'✗')+' <b>'+h(t.name)+'</b> – '+h(t.detail||'')+'</div>').join('');mstat.textContent=j.ok?'OK':'FEHLER';mstats.textContent=j.ok?'Alles in Ordnung':(j.summary?.failed||0)+' Fehler'}catch(e){test.innerHTML='<span class="bad">'+h(e.message)+'</span>'}}
async function watchdog(){try{let j=await (await fetch('debug.cgi?action=watchdog',{cache:'no-store'})).json(),w=j.watchdog||{};wd.innerHTML='<b>Status:</b> '+(w.ok?'<span class="ok">OK</span>':'<span class="bad">Fehler/kein Status</span>')+'<br><b>Letzter Erfolg:</b> '+(w.last_success?new Date(w.last_success*1000).toLocaleString():'–')+'<br><b>Antwortzeit:</b> '+(w.response_ms??'–')+' ms<br><b>Fehlerfolge:</b> '+(w.consecutive_failures??'–');mwd.textContent=w.ok?'OK':'–';mwds.textContent=w.timestamp?'Letzte Prüfung: '+new Date(w.timestamp*1000).toLocaleTimeString():'Kein Status'}catch(e){}}
async function logLoad(){try{let j=await (await fetch('debug.cgi?action=read&lines=100',{cache:'no-store'})).json();log.textContent=(j.lines||[]).reverse().join('\n')||'Noch keine Logeinträge.'}catch(e){}}
async function logClear(){if(confirm('Log wirklich leeren?')){await fetch('debug.cgi?action=clear',{cache:'no-store'});logLoad()}}
renderGroups();loadDevices();selftest();watchdog();logLoad();setInterval(watchdog,30000);
</script>~;
LoxBerry::Web::lbfooter();
